Rb photogram industrial 2
hcontr4/photogram-industrial pull request #2
Opened 2024-07-02 13:54 UTC by hcontr4

Git commits up to part 2.

2024-07-02 13:57 UTC, rayguna approved these changes
Looks good. The schema.db and the models files looks complete.

2024-07-02 14:56 UTC, thierrychau requested changes
Hi Herman, great job with implementing all these resources. I have a few minor comments, please see below. Also, did you create a sample_data task?

2024-07-02 14:56 UTC, thierrychau commented on .vscode/settings.json
I'm inclined to say that this file does not need to be committed to your repo. In the future, you can either add it to your `.gitignore`, or just not stage it when you commit.

For this time, it's okay to leave.

2024-07-02 14:56 UTC, thierrychau commented on app/models/comment.rb
> +  belongs_to :photo
Can you add a counter_cache?

2024-07-02 14:56 UTC, thierrychau commented on app/models/follow_request.rb
> +  belongs_to :sender, class_name: "User"
You could greatly benefit from having an `enum` for the `status`. Can you add this?

2024-07-02 14:56 UTC, thierrychau commented on app/models/like.rb
> +  belongs_to :photo, counter_cache: true
Can you add a validation to make sure a user is not able to like the same photo more than once?

2024-07-02 14:56 UTC, thierrychau commented on app/models/user.rb
> +  has_many :sent_follow_requests, foreign_key: :sender_id, class_name: "FollowRequest"
Can you add a `dependent: :destroy` option to take care of orphan records?

2024-07-02 15:43 UTC, thierrychau approved these changes
Looks great, good to merge. Thanks for the edits.

2024-07-02 15:45 UTC, merged

2024-07-10 18:15 UTC, MauritzKurt commented
Looks complete, great job on the backend setup!